// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3QHBPI4bVTWW4vSXY_Hvgm8RCX0JlBCM',
    appId: '1:160288392531:android:2fcec758e82482a0df4da6',
    messagingSenderId: '160288392531',
    projectId: 'authnew-a3927',
    storageBucket: 'authnew-a3927.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnRN-nZXmjvTsAWxGAEfdYrSXxGpRsGEw',
    appId: '1:160288392531:web:4da3d078f9a23395df4da6',
    messagingSenderId: '160288392531',
    projectId: 'authnew-a3927',
    authDomain: 'authnew-a3927.firebaseapp.com',
    storageBucket: 'authnew-a3927.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnRN-nZXmjvTsAWxGAEfdYrSXxGpRsGEw',
    appId: '1:160288392531:web:4da3d078f9a23395df4da6',
    messagingSenderId: '160288392531',
    projectId: 'authnew-a3927',
    authDomain: 'authnew-a3927.firebaseapp.com',
    storageBucket: 'authnew-a3927.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOR9doBVTlk0FwLlpTVOaxHsovKXq4V2Q',
    appId: '1:160288392531:ios:f42c1839e85b724adf4da6',
    messagingSenderId: '160288392531',
    projectId: 'authnew-a3927',
    storageBucket: 'authnew-a3927.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOR9doBVTlk0FwLlpTVOaxHsovKXq4V2Q',
    appId: '1:160288392531:ios:f42c1839e85b724adf4da6',
    messagingSenderId: '160288392531',
    projectId: 'authnew-a3927',
    storageBucket: 'authnew-a3927.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication3',
  );

}